// frontend_react/src/page/auth/inicio_sesion.jsx
import { Link, useNavigate } from "react-router-dom";
import apiService from "../../services/conexio";
import { useState } from "react";
import "../../styles/inicioSecion.css";
const Inicio_sesion = () => {
    const navigation = useNavigate();

    const [data, setData] = useState({ email_usuario: "", contra_usuario: "" });

    const ingresar = async () => {
        console.log(data);
        const resepcion = await apiService.fetchData(
            "POST",
            "login",
            data,
            undefined
        );
        if (resepcion.data.message === "Usuario Valido") {
            navigation("/");
        } else {
            alert(resepcion.data.message);
        }
    };

    return (
        <div className="padre">
            <section className="section_ssesion">
                <h1>Inicie su Sesión </h1>

                <form action="" className="formulario">
                    <input
                        type="text"
                        name="email"
                        required
                        placeholder="Gmail"
                        title="Debe contener @"
                        value={data.email_usuario}
                        onChange={(e) =>
                            setData((old) => ({ ...old, email_usuario: e.target.value }))
                        }
                    />

                    <input
                        type="password"
                        name="contraseña"
                        placeholder='Contraseña' required  
                        maxLength= '50' 
                        minLength="7"
                        value={data.contra_usuario}
                        onChange={(e) =>
                            setData((old) => ({ ...old, contra_usuario: e.target.value }))
                        }
                    />
                </form>

                <button className="boton_sesion" onClick={() => ingresar()}>
                    Iniciar Sesión
                </button>
                <br />
                <br /><br />
                <span>
                    No tengo un cuenta<Link to="/Registro" className="p"> Registrate</Link>
                </span>
            </section>
        </div>
    );
};

export default Inicio_sesion;

// frontend_angular/src/app/inicio-sesion/inicio-sesion.component.ts
import { Component } from '@angular/core';
import { Router, RouterLink, RouterOutlet } from '@angular/router';
import { ButtonModule } from 'primeng/button';
import { PasswordModule } from 'primeng/password';

@Component({
  selector: 'app-inicio-sesion',
  standalone: true,
  imports: [ButtonModule, PasswordModule,RouterLink ,RouterOutlet],
  templateUrl: './inicio-sesion.component.html',
  styleUrl: './inicio-sesion.component.css'
})
export class InicioSesionComponent {
  constructor(private router:Router) {}
  redirect(){
    this.router.navigate(['/home'])
  }
}

<div class="padre">
    <section class="container">
        <br><br>
        <h1>Inicio de Sesión</h1>
    
        <form action="#">
    
            <div class="form-control">
                <input type="text" name="email" required placeholder="Gmail" title="Debe contener @">
                <input name="password" type="password" required placeholder="Contraseña" maxlength="50" minlength="6">
                
            </div>
    
    
    
            <button class="btn"  (click)="redirect()">Iniciar Sesion</button>
            
            <br><br>
            <span> No tengo una cuenta <a routerLink="/registro"> Registrarse</a></span>
        </form>
    
    </section>
</div>

<router-outlet></router-outlet>
