// frontend_react/src/components/footer.jsx
import "../styles/footer.css"

const Footer = () => {
    return (
        <footer>
            <div className="carrito">
                <img src="" alt="" />
            </div>

            <section className="redondo_img">
                <img src="../assets/whatsapp.png" alt="" className="img"/>
                <img src="" alt="" className="img"/>
                <img src="" alt="" className="img"/>

                <p>Derechos Reservados &copy; 2024 </p>
            </section>



            <div>
                <p>Numeros de Referencia</p>

                <p>Gerente: 45487894</p>
                <p>Soporte Tecnico: 67562659</p>
            </div>

            <div >
            <p>Politicas de Privacidad</p>
            <p>Terminos de Servicio</p>

            </div>

        </footer>
    )
}

export default Footer

// frontend/src/app/footer/footer.component.ts
import { Component } from '@angular/core';


@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css'
})
export class FooterComponent {

  
}

<footer>
    <section>
        <img src="../../img/iconos/icono_Whatsapp.svg" alt="">
        <img src="../../img/iconos/icono_instagram.svg" alt="">
        <img src="../../img/iconos/icono_Facebook.svg" alt="">
        <p>Derechos Reservados &copy; 2024 </p>

    </section>

    <div >
        <p>
            Numeros de referencia
        </p>
        <p>Politicas de Privacidad</p>
        <p>Gerente: 4585967</p>
        <p>Terminos de Servicio</p>
        <p>Soporte: 67562659</p>
    </div>


</footer>
